Fix clang-format run.
clang-format without options always prints to stdout, so the previous
check with astyle couldn't be swapped in. This updates the check to
be a little more path friendly.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -53,15 +53,30 @@ addons:
 before_install:
     - |
       if [ "${CHECK_STYLE}" == "ON" ] ; then
-          echo "Checking coding style with clang-format..."
-          clang-format $(find NFIQ2 \( -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \) -a \! -path '*wsq*' -a \! -name 'RandomForestTrainedParams.h') > clang-format.out
-          if [ $(cat clang-format.out | wc -l | tr -d -C '[:digit:]') -ne 0 ]; then
-              cat clang-format.out
-              git --no-pager diff
-              echo "Please run the above files through clang-format using the .clang-format configuration and push your changes to the same branch."
+          echo -n "Checking coding style with clang-format..."
+
+          fail=0
+          while read -r i; do
+              if ! clang-format --Werror --dry-run "${i}" > /dev/null 2>&1;
+              then
+                  if [ "${fail}" == "0" ]; then
+                      echo "[FAIL]"
+                  fi
+                  fail=1
+                  echo "Please run clang-format -i ${i}"
+              fi
+          done < <(find NFIQ2 \( -name "*.c" -o -name "*.h" \
+              -o -name "*.cpp" -o -name "*.hpp" \) -a \! -path '*wsq*' \
+              -a \! -name 'RandomForestTrainedParams.h')
+
+          if [ "${fail}" == "1" ]; then
+              msg="Please run the above files through clang-format using the "
+              msg+=".clang-format configuration and push your changes to the "
+              msg+="same branch. See CONTRIBUTING.md for more information."
+              echo "${msg}"
               exit 1
           else
-              echo "clang-format finished with no changes"
+              echo "[OKAY]"
           fi
       fi
 
